# Generated by Django 3.0.6 on 2020-05-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Quiz author', 'Quiz author'), ('Player', 'Player')], default=False, max_length=15),
        ),
    ]
